### ISSUE TITLE
eurecom.fr offline?

### ISSUE THREAD

**Issue by nightcore125** [OPENAIRINTERFACE/openair-cn#100]
Currently neither eurecom.fr nor gitlab.eurecom.fr seems to be available. Unfortunately, the installation of the software dependencies fails due to the unavailability of the gitlab server. Does anyone know what is going on?

> Cloning into '/tmp/asn1c'...
fatal: unable to access 'https://gitlab.eurecom.fr/oai/asn1c.git/': Failed to connect to gitlab.eurecom.fr port 443: Connection timed out
/root/openair-cn/build/tools/build_helper: line 823: ./configure: No such file or directory
make: *** No rule to make target 'install'.  Stop.
Error: MME software installation failed

**Comment by lionelgo** [comment]
Yes, almost 2 times in the evening CET, this week EURECOM infra was not 
accessible, now seems OK.
