### ISSUE TITLE
build_cassandra no longer working

### ISSUE THREAD

**Issue by pemmoura** [OPENAIRINTERFACE/openair-cn#103]
The https://launchpad.net/~webupd8team/+archive/ubuntu/java repository has been discontinued due to licensing, the script is unable to download java.

Also, the GPG key download for cassandra repository isn't working anymore:

curl https://www.apache.org/dist/cassandra/KEYS | $SUDO  apt-key add -

**Comment by Rukyr97** [comment]
https://github.com/OPENAIRINTERFACE/openair-cn/issues/58

check this issue, it solved the problem to me!

**Comment by pemmoura** [comment]
@Rukyr97 thanks. It seems that the official keys file for cassandra has changed url, as stated in http://cassandra.apache.org/download/.

https://downloads.apache.org/cassandra/KEYS

so the:
curl https://www.apache.org/dist/cassandra/KEYS | $SUDO apt-key add - 
should be changed to:
curl https://downloads.apache.org/cassandra/KEYS | $SUDO apt-key add -
