### ISSUE TITLE
HSS not working on ubuntu 18.04

### ISSUE THREAD

**Issue by pemmoura** [OPENAIRINTERFACE/openair-cn#104]
A new compiled HSS with ubuntu 18.04 isn't working. Previously compiled code works fine.
After debugging, the execution stops at:

openair-cn/src/hss_rel14/src/fdhss.cpp:125
...
m_dbobj.connect(hss_config_p->cassandra_server);
...

The issue seems related to gcc 7.5.0, which has been updated in ubuntu 18.04 recently. Compiling with 7.4.0 works fine. However, new installed ubuntu will download gcc7.5.0.

Following logs of compiling and execution.

[build_hss.log](https://github.com/OPENAIRINTERFACE/openair-cn/files/4357009/build_hss.log)
[hss.log](https://github.com/OPENAIRINTERFACE/openair-cn/files/4356960/hss.log)

**Comment by lionelgo** [comment]
Thanks for reporting, we will check this.

**Comment by pemmoura** [comment]
Updating. The installation doesn't work on ubuntu 16.04 with gcc5.4 also. Probably not related to gcc version.

**Comment by pemmoura** [comment]
A commit in cpp-driver submodule git made hss not functional.

Got it to work by adding 'git checkout 2.15.0' at openair-cn/build/tools/build_helper.hss_rel14:

build_cpp_driver()
{
  pushd $OPENAIRCN_DIR/build/git_submodules/cpp-driver
  **git checkout 2.15.0**
  rm -rf build
  mkdir -p build
  cd build
  $CMAKE ..
  res=$?
  [[ $res -ne 0 ]] && popd && return $res
  make
  res=$?
  [[ $res -ne 0 ]] && popd && return $res
  $SUDO make install
  res=$?
  [[ $res -ne 0 ]] && popd && return $res
  popd
  return $?
}

**Comment by lionelgo** [comment]
Thanks a lot for your work, Raphael is testing your suggestion.

**Comment by rdefosse** [comment]
Hello Pedro (@pemmoura)

I made a patch on the `develop` branch. It was something I stumble upon on Friday and I was planning to debug today. 

**Thanks a lot for sparing me a painful debug session**

Regards
Raphael
