### ISSUE TITLE
MME compilation failed

### ISSUE THREAD

**Issue by EboYu** [OPENAIRINTERFACE/openair-cn#28]
I tried to deploy a EPC in a virtual machine with Ubuntu 16.04 and the 4.9.108 kernel.  I followed the installation instructions in https://github.com/OPENAIRINTERFACE/openair-cn/wiki/Basic-Deployment-of-vEPC to build the openair-cn code in its develop branch and commit 1c3730e0623be220aa680ba87387ddd5cb96ac69. However, I can not pass the MME compilation and got the log messages as I attached in the following link:
[mme.txt](https://github.com/OPENAIRINTERFACE/openair-cn/files/2637568/mme.txt)
[CMakeError.log](https://github.com/OPENAIRINTERFACE/openair-cn/files/2637584/CMakeError.log)

Can you please help figure out these issues. This is a urgent request, so any help fixing this is greatly greatly appreciated.

**Comment by lionelgo** [comment]
Hello,
You do not have the right version of nettle installed.
I am checking if something was changed recently...

**Comment by lionelgo** [comment]
Seems to me that nettle installation did not change during last 6 months, did you do "build_mme -i" ?

**Comment by EboYu** [comment]
> Seems to me that nettle installation did not change during last 6 months, did you do "build_mme -i" ?
Thanks for your response. Yes, before executing "./build_mme", I have done "./build_mme -i -f".  All related software has been installed.

**Comment by EboYu** [comment]
I have addressed this problem by manually deleting and reinstalling nettle. Thanks so much.
