### ISSUE TITLE
Missing freeDiameter repo in opencoord

### ISSUE THREAD

**Issue by muralir-nv** [OPENAIRINTERFACE/openair-cn#32]
There is a failure doing this:
./build_hss_rel14 --check-installed-software --force

The repo https://gerrit.opencord.org/freeDiameter.git is missing.

When I change ".git/config" to pick old freeDiameter https://gitlab.eurecom.fr/oai/freediameter.git
the corresponding commit is not there:

Entering '../build/git_submodules/spdlog'
HEAD is now at 0955ea5 Merge pull request #945 from cneumann/fix-external-fmt
error: Server does not allow request for unadvertised object 13d9601bf947af3286764506368fc3d04672bfde
Fetched in submodule path '../build/git_submodules/freeDiameter', but it did not contain 13d9601bf947af3286764506368fc3d04672bfde. Direct fetching of that commit failed.
Error: HSS software installation failed

Is this a known issue? Will the opencoord repo be back or what else need to change?

**Comment by cornacchia** [comment]
I'm having the same problem trying to build the mme
`scripts/build_mme -i`
```
...
Cloning into 'build/git_submodules/freeDiameter'...
fatal: remote error: Git repository not found
fatal: clone of 'https://gerrit.opencord.org/freeDiameter.git' into submodule path 'build/git_submodules/freeDiameter' failed
```

**Comment by mathieuxilan** [comment]
Hi,

Do you mean in .gitmodules ? 

btw, as I was able to compile the hssn but not the mme, does it mean that the mme and the hss do not use the same diameter server ?

**Comment by mathieuxilan** [comment]
I successfully compiled the mme thanks to your comment, but then I have this error when I try to run it:

`Extension /usr/local/lib/freeDiameter/dict_S6as6d.fdx returned an error during initialization: No such file or directory`

do you have the same error ?

**Comment by cornacchia** [comment]
I get these warnings when i launch it, but then it works fine.
```
...... 00000:115586 7F99A9A5C740 LEVEL S6A --no source file-- Unable to  resolve symbol 'fd_ext_init2' for extension /usr/local/lib/freeDiameter/dict_nas_mipv6.fdx:
...... 00000:115592 7F99A9A5C740 LEVEL S6A --no source file-- Unable to  resolve symbol 'fd_ext_init2' for extension /usr/local/lib/freeDiameter/dict_s6a.fdx:
```
I checked under `/usr/local/lib/freeDiameter` and `dict_S6as6d.fdx` is in there though. From your error it looks like you're missing it for some reason.

**Comment by mathieuxilan** [comment]
ok, I'll try to compile the mme from scratch then, maybe I made something wrong in a previous attempt. 
Do you run the mme and the hss on the same server ?

**Comment by cornacchia** [comment]
Yup I run both of them on a Ubuntu server 16.04 machine, branch develop.

**Comment by muralir-nv** [comment]
I sync'ed code now and no longer face the issue. So closing. Thank you.
