### ISSUE TITLE
No Network devices 

### ISSUE THREAD

**Issue by mikewell** [OPENAIRINTERFACE/openair-cn#33]
We are following the instruction step by step. When we going through the following section:

Network devices

ens3 to ens10 is enought (no need for ens11..ens15)

when we type "ip link show",

we see only lo and ens3. Is this normal or should we add the devices manually?

Thanks.

**Comment by lionelgo** [comment]
Just add the network devices through your virtual machine manager.

**Comment by mikewell** [comment]
Thanks a lot.
