### ISSUE TITLE
libapache error in build_hss script

### ISSUE THREAD

**Issue by Shashank6669** [OPENAIRINTERFACE/openair-cn#43]
I'm trying to run the build_hss script and facing libapache dependency errors. I'm unable to resolve them by installing the packages independently. I'm using an ubuntu 14.04.3 LTS with the recommended low latency kernel. Any help will be appreciated. Thanks.

**Comment by Shashank6669** [comment]
Here is the screenshot of the error for reference:
file:///home/testbed5g/Desktop/Screenshot%20from%202019-02-13%2014:47:39.png

**Comment by Shashank6669** [comment]
Here is a snippet of the error I'm facing:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libapache2-mod-php5filter' for regex 'libapache2-mod-php*'
Note, selecting 'libapache2-mod-php4' for regex 'libapache2-mod-php*'
Note, selecting 'libapache2-mod-php5' for regex 'libapache2-mod-php*'
python-pexpect is already the newest version.
python-pexpect set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libapache2-mod-php5 : Conflicts: libapache2-mod-php5filter but 5.5.9+dfsg-1ubuntu4.26 is to be installed
 libapache2-mod-php5filter : Conflicts: libapache2-mod-php5 but 5.5.9+dfsg-1ubuntu4.26 is to be installed
E: Unable to correct problems, you have held broken packages.
HSS not compiled, to compile it, re-run build_hss without -i option

**Comment by lionelgo** [comment]
This does not occur on Ubuntu bionic, openair-cn tag v1.0.0.
Please use Ubuntu Bionic for any CN component (tag v1.0.0).
You will have to install HSS, MME from openair-cn repo
You will have to install SPGW from openair-cn-cups repo, also tag v1.0.0.
