### ISSUE TITLE
MME build "mme compilation failed" and "auth_request compliation failed"

### ISSUE THREAD

**Issue by omeshF** [OPENAIRINTERFACE/openair-cn#48]
Hello
I'm using Ubuntu 14.04 on Vmware and have installed and configured HSS and upon installation and build of mme, I'm presented with the following error. 
./build_mme --clean
Clean the build generated files (build from scratch)
mkdir: created directory ‘BUILD’
Build type is Debug
Architecture is x86_64
git found: /usr/bin/git
mme compilation failed
cp: cannot stat ‘/home/omesh/openair-cn/BUILD/MME/BUILD/mme’: No such file or directory
auth_request compilation failed
cp: cannot stat ‘/home/omesh/openair-cn/BUILD/MME/BUILD/auth_request’: No such file or directory

I have run the command ./build_mme -i previously. Also I have re-installed nettle-dev

Awaiting a response from earliest.
Thank you

**Comment by lionelgo** [comment]
Please use Ubuntu bionic arch=amd64, Ubuntu 14.04 and 16.04 are no more supported.
Install HSS, MME from openair-cn repo, tag v1.0.0
Install SPGW from openair-cn-cups repo, tag v1.0.0
I am currently writing the installation procedure on the WIKI.
