### ISSUE TITLE
Error parsing JSON config file 

### ISSUE THREAD

**Issue by ChouZak** [OPENAIRINTERFACE/openair-cn#49]
![json file in edited](https://user-images.githubusercontent.com/50944290/58235949-c9936a00-7d39-11e9-9b39-21d64a49018a.PNG)
I've installed the oai_hss successfully but i cannot run the HSS .
It says : error parsing the json config file
            OPC calculation failed
I can't seem to find what's wrong with the json file

If anyone could help, Thanks !

![running HSS bug 2](https://user-images.githubusercontent.com/50944290/58235580-feeb8800-7d38-11e9-8678-69b18d2f6c5c.PNG)

**Comment by toanwhatsup** [comment]
Hi man, I ran into the same problem as well. Did you find the way to fix this?
Thanks.

**Comment by lfarizav** [comment]
Hi,

To solve this problem you can go to the file /usr/local/etc/oai/hss_rel14.json.
Then update the values:
{"common": {
    "fdcfg": "/usr/local/etc/oai/freeDiameter/hss_rel14_fd.conf",
    "originhost": "hss.ng4T.com",
    "originrealm": "ng4T.com" 
 },
 "hss": {
    "gtwhost": "*",
    "gtwport" : 9080,
    "restport" : 9081,
    "ossport" : 9082,
    "casssrv": "127.0.0.1", 
    "cassusr": "root",
    "casspwd": "root",
    "cassdb" : "vhss",
    "casscoreconnections" : 2,
    "cassmaxconnections" : 8,
    "cassioqueuesize" : 32768,
    "cassiothreads" : 2,    
    "randv"  : true,
    "optkey" : "1006020f0a478bf6b699f15c062e42b3",
    "reloadkey"  : false,
    "roamallow"  : true,
    "logsize": 20,
    "lognumber": 5,
    "logname": "logs/hss.log",
    "logqsize": 8192,
    "statlogsize": 20,
    "statlognumber": 5,
    "statlogname": "logs/hss_stat.log",
    "auditlogsize": 20,
    "auditlognumber": 5,
    "auditlogname": "logs/hss_audit.log",
    "statfreq": 2000,
    "numworkers": 4,
    "concurrent": 10,
    "ossfile": "conf/oss.json"    
 }
}
I hope this can help you
