### ISSUE TITLE
./hss.conf: 10: ./hss.conf: declare: not found

### ISSUE THREAD

**Issue by omeshF** [OPENAIRINTERFACE/openair-cn#50]
Hello, 

I'm following instructions at https://github.com/OPENAIRINTERFACE/openair-cn/wiki/OpenAirSoftwareSupport and using Ubuntu 18.04 bionic version. 
I'm at the step **Create HSS configuration files**. 

Hence I created an executable hss.conf and copied the following.

# prompt has been removed for easier Ctrl+C Ctrl+V
# cd $OPENAIRCN_DIR/scripts
PREFIX='/usr/local/etc/oai'
sudo mkdir -m 0777 -p $PREFIX
sudo mkdir -m 0777    $PREFIX/freeDiameter
# freeDiameter configuration files
cp ../etc/acl.conf ../etc/hss_rel14_fd.conf $PREFIX/freeDiameter
cp ../etc/hss_rel14.conf ../etc/hss_rel14.json $PREFIX

declare -A HSS_CONF
HSS_CONF[@PREFIX@]=$PREFIX
HSS_CONF[@REALM@]='ng4T.com'
HSS_CONF[@HSS_FQDN@]="hss.${HSS_CONF[@REALM@]}"
HSS_CONF[@cassandra_Server_IP@]='127.0.0.1'
HSS_CONF[@OP_KEY@]='1006020f0a478bf6b699f15c062e42b3'
HSS_CONF[@ROAMING_ALLOWED@]='true'
HSS_CONF[@cassandra_Server_IP@]='127.0.0.1'

for K in "${!HSS_CONF[@]}"; do 
  egrep -lRZ "$K" $PREFIX | xargs -0 -l sed -i -e "s|$K|${HSS_CONF[$K]}|g"
done

### freeDiameter certificate
../src/hss_rel14/bin/make_certs.sh hss ${HSS_CONF[@REALM@]} $PREFIX

# Finally customize the listen address of FD server
# set in $PREFIX/freeDiameter/hss_rel14_fd.conf and uncomment the following line
sed -i -e 's/#ListenOn/ListenOn/g' $PREFIX/freeDiameter/hss_rel14_fd.conf

when I run sudo ./hss.conf; I get the following error. 

./hss.conf: 10: ./hss.conf: declare: not found
./hss.conf: 11: ./hss.conf: HSS_CONF[@PREFIX@]=/usr/local/etc/oai: not found
./hss.conf: 12: ./hss.conf: HSS_CONF[@REALM@]=ng4T.com: not found
./hss.conf: 13: ./hss.conf: Bad substitution

Awaiting a response. 
Thank you in advance. 
Kind Regards
Omesh

**Comment by lionelgo** [comment]
I do not understand why you want to run "sudo ./hss.conf" ?  This is just a config file, not a script file.
You have to run just once 
oai_hss -j $PREFIX/hss_rel14.json --onlyloadkey
Then run 
oai_hss -j $PREFIX/hss_rel14.json

**Comment by ChouZak** [comment]
Hello, I've been following these same instructions and at this step when i run:
oai_hss -j $PREFIX/hss_rel14.json
I always get a parsing error,

Error parsing the json config file
options::parse() failed

I can't find what is the issue.
if you can help please.
Thanks in advance.

**Comment by omeshF** [comment]
Hello @lionelgo . Thank you for your response. So that I understand, could you be kind in explaining something for me. After receiving this output, 
**vhss.mmeidentity truncated
vhss.mmeidentity_host truncated
3 mme-isdn mme.ng4T.com ng4T.com 1
3 mme-isdn mme.ng4T.com ng4T.com 1**

1) Do I create a hss.conf at ~/openair-cn/scripts or in any other location and copy paste the content PREFIX='/usr/local/etc/oai'
sudo mkdir -m 0777 -p $PREFIX....?
2) Or Do i issue the command?
**~/openair-cn/scripts$ oai_hss -j $PREFIX/hss_rel14.json --onlyloadkey** in which i get an error 
_The json config file specified does not exists
Options::parse() failed_

I would deeply appreciate it if you could kindly assist me in this regard. 
Thank you

**Comment by shumbac** [comment]
> Hello, I've been following these same instructions and at this step when i run:
> oai_hss -j $PREFIX/hss_rel14.json
> I always get a parsing error,
> 
> Error parsing the json config file
> options::parse() failed
> 
> I can't find what is the issue.
> if you can help please.
> Thanks in advance.
hi Im getting the same error. did you finally manage to encounter it?
