### ISSUE TITLE
data_provisioning_users is failing - cassandra.cluster.NoHostAvailable

### ISSUE THREAD

**Issue by manunok** [OPENAIRINTERFACE/openair-cn#74]
Hello,
I'm trying to install openair-cn on a Ubuntu Bionic VM. I followed the guide :https://github.com/OPENAIRINTERFACE/openair-cn/wiki/OpenAirSoftwareSupport. This VM is located in an openstack Newton private cloud.

I kept the localhost default config during the Cassandra installation. It seems my Cassandra DB is ok as I can connect and I see the vhss keyspace

> root@osccbis-1:~/openair-cn# cqlsh 127.0.0.1
> Connected to Test Cluster at 127.0.0.1:9042.
> 
> cqlsh> SELECT * FROM system.schema_keyspaces WHERE keyspace_name = 'vhss' ;
> 
>  keyspace_name | durable_writes | strategy_class                                       | strategy_options
> ---------------+----------------+------------------------------------------------------+------------------
>           vhss |           True | org.apache.cassandra.locator.NetworkTopologyStrategy |      {"DC1":"1"}
> 

But when I launch the data_provisisioning_users script, it fails telling "Unable to complete the operation against any hosts".

> root@osccbis-1:~/openair-cn/scripts# ./data_provisioning_users --apn default.ng4T.com --apn2 internet --key fec86ba6eb707ed08905757b1bb44b8f --imsi-first 208931234561000 --msisdn-first 001011234561000 --mme-identity mme.ng4T.com --no-of-users 20 --realm ng4T.com --truncate True  --verbose True --cassandra-cluster $Cassandra_Server_IP
> Traceback (most recent call last):
>   File "./data_provisioning_users", line 178, in <module>
>     main()
>   File "./data_provisioning_users", line 155, in main
>     '{"Subscription-Data":{"Access-Restriction-Data":41,"Subscriber-Status":0,"Network-Access-Mode":2,"Regional-Subscription-Zone-Code":["0x0123","0x4567","0x89AB","0xCDEF","0x1234","0x5678","0x9ABC","0xDEF0","0x2345","0x6789"],"MSISDN":"0x'+str(msisdn)+'","AMBR":{"Max-Requested-Bandwidth-UL":50000000,"Max-Requested-Bandwidth-DL":100000000},"APN-Configuration-Profile":{"Context-Identifier":0,"All-APN-Configurations-Included-Indicator":0,"APN-Configuration":{"Context-Identifier":0,"PDN-Type":0,"Service-Selection":"'+args.apn+'","EPS-Subscribed-QoS-Profile":{"QoS-Class-Identifier":9,"Allocation-Retention-Priority":{"Priority-Level":15,"Pre-emption-Capability":0,"Pre-emption-Vulnerability":0}},"AMBR":{"Max-Requested-Bandwidth-UL":50000000,"Max-Requested-Bandwidth-DL":100000000},"PDN-GW-Allocation-Type":0,"MIP6-Agent-Info":{"MIP-Home-Agent-Address":["172.26.17.183"]}},"APN-Configuration":{"Context-Identifier":0,"PDN-Type":0,"Service-Selection":"'+args.apn2+'","EPS-Subscribed-QoS-Profile":{"QoS-Class-Identifier":9,"Allocation-Retention-Priority":{"Priority-Level":13,"Pre-emption-Capability":1,"Pre-emption-Vulnerability":0}},"AMBR":{"Max-Requested-Bandwidth-UL":50000000,"Max-Requested-Bandwidth-DL":100000000},"PDN-GW-Allocation-Type":0,"MIP6-Agent-Info":{"MIP-Home-Agent-Address":["172.26.17.183"]}}},"Subscribed-Periodic-RAU-TAU-Timer":0}}'
>   File "/usr/lib/python3/dist-packages/cassandra/cluster.py", line 1998, in execute
>     return self.execute_async(query, parameters, trace, custom_payload, timeout, execution_profile, paging_state).result()
>   File "/usr/lib/python3/dist-packages/cassandra/cluster.py", line 3781, in result
>     raise self._final_exception
> cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.0.0.1 datacenter1>: Unavailable('Error from server: code=1000 [Unavailable exception] message="Cannot achieve consistency level LOCAL_ONE" info={\'consistency\': \'LOCAL_ONE\', \'required_replicas\': 1, \'alive_replicas\': 0}',)})
> 

Do you have any idea why? I cannot see how to debug this.

**Comment by openairinterface-GH** [comment]
Hello,
This is not an issue of the OAI code, but a configuration problem, please use the openair-cn user mailing list for this purpose, Regards.

**Comment by manunok** [comment]
Hello Thanks for your answer. Could you tell me how to use the openair-cn user mailing list?

**Comment by manunok** [comment]
ok, it's actually explained: https://gitlab.eurecom.fr/oai/openairinterface5g/wikis/MailingList
If you consider it's not a bug, you can close this ticket

**Comment by Uldanay** [comment]
Hello @manunok 
Sorry for disturbing. 
Did you solve the problem? I have exactly the same issue. If yes, could you share with solution ?
Thanks!
