### ISSUE TITLE
OAI HSS not running 

### ISSUE THREAD

**Issue by TahaM** [OPENAIRINTERFACE/openair-cn#79]
Followed the steps in https://github.com/OPENAIRINTERFACE/openair-cn/wiki/OpenAirSoftwareSupport
But when run HSS with command oai_hss -j $PREFIX/hss_rel14.json --onlyloadkey i get 
Options::parse() failed

**Comment by jrmejiaa** [comment]
@TahaM how did you fix the error? I have the same problem
