### ISSUE TITLE
Create session failure with fault: REMOTE_PEER_NOT_RESPONDING

### ISSUE THREAD

**Issue by bwchacha** [OPENAIRINTERFACE/openair-cn#80]
I'm using master verion of openair-cn-cups as spgw part, two real enb and Huawei CPE for test.
When UE tried to attach, it failed with error indication: REMOTE_PEER_NOT_RESPONDING.
By walking through the code, the error indication is located at pgwc_procedure.cpp line 88: 
int session_establishment_procedure::run(std::shared_ptr<itti_s5s8_create_session_request>& req,
    std::shared_ptr<itti_s5s8_create_session_response>& resp,
    std::shared_ptr<pgwc::pgw_context> pc)
{
  // TODO check if compatible with ongoing procedures if any
  pfcp::node_id_t up_node_id = {};
  if (not pfcp_associations::get_instance().select_up_node(up_node_id, NODE_SELECTION_CRITERIA_MIN_PFCP_SESSIONS)) {
    // TODO
    ::cause_t cause = {};
    cause.pce = 1;
    cause.cause_value = REMOTE_PEER_NOT_RESPONDING;
    resp->gtp_ies.set(cause);
    return RETURNerror;
  }

I added some print log to check the cause and found the code returned error at the very beginning of the function at: 
 if (not pfcp_associations::get_instance().select_up_node(up_node_id, NODE_SELECTION_CRITERIA_MIN_PFCP_SESSIONS)) 

Then, by checking function 'select_up_node()' , it seems 'association.empty()' is true, which means there is no association is founded. I also checked all other funtions in pgw_pfcp_association.cpp, and found funtions like 'pfcp_associations::add_association' and 'pfcp_associations::get_association' were not invoked during UE attach. Is that mean there is something wrong to get 'association'?

Attached file is the log when UE tried attach. Anyone could help on this issue is much appreciated!
[fail log1.zip](https://github.com/OPENAIRINTERFACE/openair-cn/files/3887137/fail.log1.zip)

**Comment by lionelgo** [comment]
Hello,

Seems SPGW-C is not reachable by SPGW-U on SX interface?

Regards,

Lionel Gauthier.

**Comment by bwchacha** [comment]
@lionelgo 
From trace log, it probably shows SPGW-U is not reponding on SX interface. My testlab configuration and topology is shown in attached files, where you can see I have set SX, S11-C, S5/S8 interfaces in the same subnet on ens255f0 subinterfaces. 
Is there any IP planning requirements on setting up SX interface? 
[oai_config.zip](https://github.com/OPENAIRINTERFACE/openair-cn/files/3890322/oai_config.zip)

**Comment by bwchacha** [comment]
@lionelgo 
I tried to change SX interface on PGW-C from ens255f0:7 to ens255f1:7 which make both ends of SX interface located on different NIC but still remains in the same IP subnet. The problem remains the same, no reponding from SX interface.
Wired thing is that mme.log I uploaded in last comment (line No. 002419) shows UE connected to network just for a short while.
This problem borthered me for almost a month......
Much appreciated if you could help me on this issue.
Many thanks.

**Comment by lionelgo** [comment]
Just do thing simple: try to set SX on "lo" interface for example PGW-C Sx IP=127.55.1.113, SPGW-U Sx IP=127.55.1.123

**Comment by bwchacha** [comment]
@lionelgo 
Just set both SX endpoints on "lo" interface, PGW-C SX IP: 127.0.1.7, SPGW-U SX IP = 127.0.1.8, problem still remains as before.
Maybe it is not caused by subnet of SX interface?
There is an warning log before 'sx_session_restore_procedure':
PCO: Protocol/container identifier 0x0003 not supported now

Is it anything to do with this?
Thanks.
[fail log4-sxloif.zip](https://github.com/OPENAIRINTERFACE/openair-cn/files/3892117/fail.log4-sxloif.zip)

**Comment by bwchacha** [comment]
Just simply use 'lo' as both endpoints of PGW-SX and SPGW-U SX is not workable, there were massive error info reported in spgwu.log:
[2019-11-27T10:36:32.216681] [spgwu] [pfcp     ] [error] PFCP IE type 0 length 0
[2019-11-27T10:36:32.217010] [spgwu] [spgwu_sx ] [info ] handle_receive exception PFCP msg 0 Bad Length hdr.length 1024/ sum ie 0 / check sum ie 1020 Exception /root/openair-cn-cups/src/pfcp/3gpp_29.244.hpp:488
[2019-11-27T10:36:32.217098] [spgwu] [spgwu_sx ] [info ] handle_receive(-1 bytes)

Yet, by using subinterfaces like 'lo:sxa' and 'lo:sxb' , there were no such error info, but attach rejected by "REMOTE_PEER_NOT_RESPONDING" as before.

**Comment by bwchacha** [comment]
@lionelgo 
hi, 
I found somthing in spgwu_sx.cpp that I may not understand.
In spgwu_sx cpp line 187: spgwu_sx::spgwu_sx () : pfcp_l4_stack(). The object 'spgwu_cfg.sx.addr4' was invoked.
But in spgwu_sx cpp line 224: for (std::vector<pfcp::node_id_t>::const_iterator it = spgwu_cfg.spgwcs.begin(); it != spgwu_cfg.spgwcs.end(); ++it)
The iterator 'it' is actually taking S11-C as node value, where I found it by printing its ipv4 address which turn out to be S11-C address. This node_id is then passed to 'start_association' in line 489.
During spgwu_sx starting, is it a mistake to take S11-C address rather than sx address in SX 'start_association' process?  Maybe that's why SX node is not reponding?
Would you pls check on this? Thanks a lot!

**Comment by lionelgo** [comment]
Hello,

Yes, you have put SPGW-C SX address in SPGW-U config file, only MME and
SPGW-C talk over S11.

Regards.

**Comment by bwchacha** [comment]
@lionelgo 
Hello,
Yes, after changing SPGW-C list in spgwu.conf, attach is ok now. Thanks a lot for your advice.
